language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      addons:
        apt:
          packages:
            - mesa-common-dev
            - libglu1-mesa-dev
            - freeglut3-dev
            - libglfw3-dev
            - libgles2-mesa-dev
            - cmake
          sources:
            - kalakris-cmake
      before_install: sudo apt-get install cmake
    - os: windows
      before_install: choco upgrade cmake

branches:
  only:
    - master

script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake ..
  - cmake --build .
  - ctest -C Debug -V
