language: cpp

matrix:
  include:
  - os: linux
    dist: bionic
    compiler: gcc
    addons:
          apt:
            packages:
              - libgl1-mesa-dev
  - os: windows

branches:
  only:
  - master

script:
- mkdir build
- cd build
- cmake ..
- cmake --build .
- ctest -C Debug -V
