language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      addons:
        apt:
          packages:
            - mesa-common-dev
            - libglu1-mesa-dev
            - freeglut3-dev
            - libglfw3-dev
            - libgles2-mesa-dev
            - cmake
      install:
        # https://github.com/ldionne/hana/blob/master/.travis.yml
        ############################################################################
        # All the dependencies are installed in ${HOME}/deps/
        ############################################################################
        - DEPS_DIR="${HOME}/deps"
        - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
        ############################################################################
        # Install a recent CMake
        ############################################################################
        - |
          CMAKE_URL="https://cmake.org/files/v3.16/cmake-3.16.0-Linux-x86_64.tar.gz"
          mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
          export PATH=${DEPS_DIR}/cmake/bin:${PATH}
        ############################################################################
        # Go back to the root of the project and setup the build directory
        ############################################################################
        - cd "${TRAVIS_BUILD_DIR}"
    - os: windows
      install: choco upgrade cmake

branches:
  only:
    - main

script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake ..
  - cmake --build .
  - ctest -C Debug -V
